import React, { useState, useEffect } from 'react';
import { RefreshCcw, Plus, Trash2, Wand2 } from 'lucide-react';
import { usePersistentState, callGAS, callGemini, getStudentColor } from '../utils/helpers';
import { UI, ConfirmModal } from '../components/SharedUI';

export default function EducationManager({ students }) {
  const [gasUrl] = usePersistentState('gas_app_url', '');
  const [selectedStudent, setSelectedStudent] = useState(null);
  const [iepData, setIepData] = useState({}); const [meetingList, setMeetingList] = useState([]); const [loading, setLoading] = useState(false); const [confirm, setConfirm] = useState(null);
  
  const fetchData = async () => { setLoading(true); const data = await callGAS(gasUrl); if(data) { const f = {}; (data.iep||[]).forEach(r => f[`${r.studentId}_${r.month}`] = r); setIepData(f); setMeetingList(data.meetings || []); } setLoading(false); };
  useEffect(() => { fetchData(); }, [gasUrl]);
  
  const saveDaily = async (studentId, month, record) => { setLoading(true); setIepData(p => ({ ...p, [`${studentId}_${month}`]: record })); await callGAS(gasUrl, { type: 'iep', studentId, month, ...record }); setLoading(false); };
  const saveMeeting = async (mData) => { setLoading(true); const nM = mData.id ? mData : { ...mData, id: Date.now() }; setMeetingList(mData.id ? meetingList.map(m => m.id === mData.id ? nM : m) : [nM, ...meetingList]); await callGAS(gasUrl, { type: 'iep_meeting', ...nM }); setLoading(false); };
  const executeDelete = async () => { const id = confirm.id; setLoading(true); setMeetingList(meetingList.filter(m => m.id !== id)); setConfirm(null); await callGAS(gasUrl, { type: 'iep_meeting', action: 'delete', id }); setLoading(false); };

  return (
    <div className="p-8 max-w-7xl mx-auto"><div className="flex justify-between items-center mb-8"><h2 className="text-3xl font-extrabold text-gray-800">개별화 교육 계획 (IEP)</h2><button onClick={fetchData} className={`p-2.5 rounded-full bg-white border shadow hover:bg-gray-50 ${loading ? 'animate-spin' : ''}`}><RefreshCcw size={20} className="text-gray-600"/></button></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">{students.map(s => (<div key={s.id} onClick={() => setSelectedStudent(s)} className={`cursor-pointer bg-white p-6 rounded-3xl shadow-lg border-4 ${getStudentColor(s.id)} hover:-translate-y-2 transition-all flex items-center gap-4`}><img src={s.photo} className="w-16 h-16 rounded-full border-2 border-white shadow-sm bg-gray-100 object-cover"/><div><div className="font-bold text-xl text-gray-800">{s.name}</div><div className="text-xs text-gray-500 mt-1">{s.grade}학년 {s.classNumber}반</div></div></div>))}</div>
      {selectedStudent && <UI.Modal onClose={() => setSelectedStudent(null)} title={`${selectedStudent.name} 학생 기록부`} maxWidth="max-w-5xl"><IEPTabContainer student={selectedStudent} iepData={iepData} meetingList={meetingList.filter(m => String(m.studentId) === String(selectedStudent.id))} onSaveDaily={saveDaily} onSaveMeeting={saveMeeting} onDeleteMeeting={(id) => setConfirm({ type: 'delete_meeting', id })} loading={loading} /></UI.Modal>}
      <ConfirmModal isOpen={!!confirm} message="이 협의록을 정말 삭제하시겠습니까? (시트에서도 삭제됩니다)" onConfirm={executeDelete} onCancel={() => setConfirm(null)} />
    </div>
  );
}

function IEPTabContainer({ student, iepData, meetingList, onSaveDaily, onSaveMeeting, onDeleteMeeting, loading }) {
  const [tab, setTab] = useState('daily');
  return <div className="h-[80vh] flex flex-col bg-gray-50"><div className="flex border-b bg-white px-6"><button onClick={() => setTab('daily')} className={`py-4 px-6 font-bold border-b-2 transition-all ${tab === 'daily' ? 'border-pink-500 text-pink-600' : 'border-transparent text-gray-400'}`}>월별 교육 기록</button><button onClick={() => setTab('meeting')} className={`py-4 px-6 font-bold border-b-2 transition-all ${tab === 'meeting' ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-400'}`}>개별화 협의록 ({meetingList.length})</button></div><div className="flex-1 overflow-hidden">{tab === 'daily' ? <IEPDailyForm student={student} data={iepData} onSave={onSaveDaily} loading={loading} /> : <IEPMeetingList student={student} list={meetingList} onSave={onSaveMeeting} onDelete={onDeleteMeeting} />}</div></div>;
}

function IEPDailyForm({ student, data, onSave, loading }) {
  const [semester, setSemester] = useState(1); const months = semester === 1 ? [3, 4, 5, 6, 7] : [8, 9, 10, 11, 12, 1]; const [activeMonth, setActiveMonth] = useState(months[0]); const [temp, setTemp] = useState({ goal: '', material: '', note: '' });
  useEffect(() => { setTemp(data[`${student.id}_${activeMonth}`] || { goal: '', material: '', note: '' }); }, [activeMonth, student, data]);
  
  return <div className="flex flex-col h-full"><div className="px-6 py-4 flex justify-between items-center bg-white border-b shrink-0"><div className="flex gap-2 overflow-x-auto custom-scrollbar">{months.map(m => (<button key={m} onClick={() => setActiveMonth(m)} className={`px-4 py-2 rounded-lg font-bold text-sm border transition-all ${activeMonth === m ? 'bg-gray-800 text-white border-gray-800' : 'bg-white text-gray-400 border-gray-200'}`}>{m}월</button>))}</div><div className="flex bg-gray-100 p-1 rounded-lg text-xs font-bold shrink-0 ml-4"><button onClick={()=>{setSemester(1);setActiveMonth(3)}} className={`px-3 py-1 rounded ${semester===1?'bg-white shadow text-pink-600':'text-gray-400'}`}>1학기</button><button onClick={()=>{setSemester(2);setActiveMonth(8)}} className={`px-3 py-1 rounded ${semester===2?'bg-white shadow text-blue-600':'text-gray-400'}`}>2학기</button></div></div><div className="flex-1 overflow-y-auto custom-scrollbar p-6 space-y-6"><div className="flex items-center justify-between pb-4 border-b border-dashed"><div className="flex items-center gap-2"><span className="text-2xl">📝</span><h3 className="font-bold text-lg">{activeMonth}월 활동 기록</h3></div><UI.Btn onClick={() => onSave(student.id, activeMonth, temp)} disabled={loading} className="py-2 px-4 text-sm">{loading ? '저장중' : '저장하기'}</UI.Btn></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><UI.Input label="🎯 이달의 목표" value={temp.goal} onChange={e=>setTemp({...temp, goal:e.target.value})} /><UI.Input label="📚 교재 및 교구" value={temp.material} onChange={e=>setTemp({...temp, material:e.target.value})} /></div><div className="flex flex-col h-64"><label className="text-xs font-bold text-gray-400 mb-1 ml-1">📝 월간 관찰 기록</label><textarea lang="ko" value={temp.note} onChange={e=>setTemp({...temp, note:e.target.value})} className="flex-1 w-full p-4 bg-yellow-50 border border-yellow-200 rounded-xl outline-none resize-none focus:ring-2 focus:ring-yellow-300" placeholder="내용 입력" /></div></div></div>;
}

function IEPMeetingList({ student, list, onSave, onDelete }) {
  const [view, setView] = useState('list'); const [editData, setEditData] = useState(null);
  const startEdit = (data) => { setEditData(data || { studentId: student.id, date: new Date().toISOString().slice(0,10), attendees: '', subjects: student.targetSubjects?.join(', ') || '', agreement: '', original: '', summary: '' }); setView('edit'); };
  
  return view === 'list' ? (<div className="flex flex-col h-full p-6"><div className="flex justify-between items-center mb-6"><h3 className="font-bold text-lg">협의록 목록</h3><button onClick={() => startEdit(null)} className="flex items-center gap-2 px-4 py-2 bg-blue-500 text-white rounded-xl font-bold hover:bg-blue-600"><Plus size={18}/> 새 협의록 작성</button></div><div className="flex-1 overflow-y-auto custom-scrollbar space-y-3">{list.length > 0 ? list.map(m => (<div key={m.id} onClick={() => startEdit(m)} className="bg-white border rounded-xl p-4 hover:shadow-md cursor-pointer transition-all flex justify-between items-center"><div><div className="font-bold text-gray-800 mb-1">{m.date} 협의회</div><div className="text-xs text-gray-500 truncate max-w-md">{m.attendees} 참석 / {m.subjects}</div></div><button onClick={(e) => {e.stopPropagation(); onDelete(m.id)}} className="p-2 text-gray-300 hover:text-red-500"><Trash2 size={16}/></button></div>)) : <div className="text-center text-gray-400 py-10">작성된 협의록이 없습니다.</div>}</div></div>) : (<IEPMeetingForm student={student} initialData={editData} onSave={d => { onSave(d); setView('list'); }} onCancel={() => setView('list')} />);
}

function IEPMeetingForm({ student, initialData, onSave, onCancel }) {
  const [form, setForm] = useState(initialData); const [aiLoading, setAiLoading] = useState(false);
  
  const toggleRole = (r) => { const roles = (form.attendees||'').split(', ').filter(x=>x); setForm({...form, attendees: roles.includes(r)?roles.filter(x=>x!==r).join(', '):[...roles,r].join(', ')}) };
  const toggleBoilerplate = (text) => { if (form.agreement.includes(text)) { setForm(prev => ({ ...prev, agreement: prev.agreement.replace(text, '').replace(/\n\n/g, '\n').trim() })); } else { setForm(prev => ({ ...prev, agreement: (prev.agreement ? prev.agreement + "\n\n" : "") + text })); } };
  
  const handleAISummary = async () => {
    const key = localStorage.getItem('google_api_key'); if(!key) return alert("설정 탭에서 Google API 키를 등록해주세요.");
    if(!form.original) return alert("회의록 원본 내용을 먼저 입력해주세요."); setAiLoading(true);
    try { const txt = await callGemini(JSON.parse(key)||key, `당신은 특수교육 전문가입니다. 다음 회의 녹취록(Raw Data)을 분석하여, '공식적인 개별화교육지원팀 협의록'에 들어갈 정돈되고 전문적인 교육 용어로 요약 정리해주세요. 문체는 건조하고 명확하게 작성하세요.\n\n[녹취록]: ${form.original}`); if(txt) setForm(p=>({...p, summary:txt})); else alert("요약 결과를 가져오지 못했습니다."); } catch(e){ alert("AI 요약 실패: " + e.message); } finally { setAiLoading(false); }
  };
  
  const BOILERPLATES = [ { label: "신체적 개입", text: "본인 및 타인의 안전을 위협하는 돌발행동(자해, 타해 등) 발생 시, 교사가 즉각적인 신체적 개입(손목 가이드, 타임아웃 등)을 통해 안전을 확보하는 것에 대해 보호자가 충분히 인지하고 동의함." }, { label: "교육과정 조정", text: "통합학급 수업 중 학생의 현행 수준과 특성을 고려하여, 특수교사가 별도의 학습지 제공 또는 수정된 과제를 제시하는 것에 동의함." }, { label: "행동 중재", text: "긍정적 행동 지원을 위해 강화물(간식, 토큰 등) 사용 및 타임아웃 절차를 적용하며, 가정에서도 일관된 지도를 연계하기로 함." }, { label: "응급 처치", text: "응급 상황 발생 시 학교의 안전 매뉴얼에 따라 조치하며, 보호자에게 즉시 연락 취함. 연락이 닿지 않을 경우 병원 이송 등에 동의함." } ];

  return (
    <div className="flex flex-col h-full bg-white"><div className="p-4 border-b flex items-center justify-between bg-gray-50"><h3 className="font-bold">📝 협의록 작성</h3><div className="flex gap-2"><button onClick={onCancel} className="px-4 py-2 bg-white border rounded-lg text-sm font-bold">취소</button><button onClick={() => onSave(form)} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-bold">저장하기</button></div></div>
      <div className="flex-1 overflow-y-auto custom-scrollbar p-6"><div className="grid grid-cols-2 gap-6 mb-6"><UI.Input label="협의 날짜" type="date" value={form.date} onChange={e => setForm({...form, date: e.target.value})} /><div><label className="block text-xs font-bold text-gray-400 mb-2 ml-1">참석자</label><div className="flex gap-3">{[{k:'parent', l:'보호자'}, {k:'special', l:'특수교사'}, {k:'homeroom', l:'담임교사'}, {k:'vice', l:'교감'}].map(r => (<button key={r.k} onClick={() => toggleRole(r.l)} className={`px-3 py-2 rounded-lg text-sm font-bold border ${(form.attendees||'').includes(r.l) ? 'bg-blue-100 border-blue-300 text-blue-700' : 'bg-gray-50 border-gray-200 text-gray-400'}`}>{r.l}</button>))}</div></div></div>
        <div className="space-y-4 mb-6"><UI.Input label="개별화교육 과목" value={form.subjects} onChange={e => setForm({...form, subjects: e.target.value})} placeholder="예: 국어, 수학" /><div><label className="block text-xs font-bold text-gray-400 mb-1 ml-1">🤝 행동 중재 및 신체적 개입 동의</label><textarea lang="ko" value={form.agreement} onChange={e => setForm({...form, agreement: e.target.value})} className="w-full p-3 bg-red-50 border border-red-100 rounded-xl text-sm focus:ring-2 focus:ring-red-200 outline-none h-24 resize-none" placeholder="협의된 동의 내용을 입력하세요." /><div className="mt-2 flex flex-wrap gap-2"><span className="text-xs font-bold text-gray-400 flex items-center mr-1">⚡ 상용구(토글):</span>{BOILERPLATES.map((bp, idx) => { const isActive = form.agreement.includes(bp.text); return <button key={idx} onClick={() => toggleBoilerplate(bp.text)} className={`px-2 py-1 rounded text-xs font-bold transition-all ${isActive ? 'bg-green-500 text-white shadow-md' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}>{isActive ? '✓ ' : ''}{bp.label}</button> })}</div></div></div>
        <div className="grid grid-cols-2 gap-6 h-64"><div className="flex flex-col"><label className="block text-xs font-bold text-gray-400 mb-1">🎤 회의록 원본 (Raw Data)</label><textarea lang="ko" value={form.original} onChange={e => setForm({...form, original: e.target.value})} className="flex-1 w-full p-3 bg-gray-50 border rounded-xl text-sm resize-none" placeholder="클로바노트 결과 등을 붙여넣으세요." /></div><div className="flex flex-col relative"><label className="block text-xs font-bold text-gray-400 mb-1">🤖 AI 요약 / 정리본</label><textarea lang="ko" value={form.summary} onChange={e => setForm({...form, summary: e.target.value})} className="flex-1 w-full p-3 bg-purple-50 border border-purple-100 rounded-xl text-sm resize-none" placeholder="AI가 요약한 내용이 여기에 들어갑니다." /><button onClick={handleAISummary} disabled={aiLoading} className={`absolute bottom-4 right-4 px-4 py-2 rounded-xl text-xs font-bold shadow-lg flex items-center gap-2 transition-all ${aiLoading ? 'bg-gray-400 text-white cursor-not-allowed' : 'bg-gradient-to-r from-blue-500 to-indigo-500 text-white hover:scale-105'}`}>{aiLoading ? <span className="animate-spin">⌛</span> : <Wand2 size={14}/>} {aiLoading ? '요약 중...' : 'Google AI 자동 요약'}</button></div></div></div>
    </div>
  );
}